[package]
name = "gba"
version = "0.1.0"
authors = ["Henry Sloan <henryksloan@gmail.com>"]
edition = "2018"

[dependencies]
cpu = { path = "../cpu" }
ppu = { path = "../ppu" }
sound = { path = "../sound" }
memory = { path = "../memory" }
bitfield = "0.13.2"
sdl2 = "0.34.3"
